pipeline {
  agent {
    label 'maven'
  }
  environment {
    template = "${TEMPLATE}"
    projectbase = "${PROJECTBASE}"
    appname = "${APPLICATION_NAME}"
    buildproject = "${projectbase}-cicd"
    testproject = "${projectbase}-test"
    prodproject = "${projectbase}-prod"
    buildconfig = "bc/${appname}"
  }
  stages {

    stage('update BuildConfig cicd project') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject("${buildproject}") {
              openshift.apply(openshift.process("-f", template, "-p NAME=${appname}", "-p SOURCE_REPOSITORY_URL=${SOURCE_REPOSITORY_URL}", "-p SOURCE_REPOSITORY_REF=${SOURCE_REPOSITORY_REF}", "-p CONTEXT_DIR=${CONTEXT_DIR}"))
            }
          }
        }
      }
    }
    stage('Build in cicd project') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject("${buildproject}") {
              myBuild = openshift.selector(buildconfig).startBuild()
              myBuild.logs("-f")
            }
          }
        }
      }
    }
    stage('Ensure DeploymentConfig exists in build project') {
      when {
        expression {
          openshift.withCluster() {
            openshift.withProject("${buildproject}") {
              return !openshift.selector("dc/${appname}").exists();
            }
          }
        }
      }
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject("${buildproject}") {
              openshift.apply(openshift.process("-f", template, "-p NAME=${appname}"))
              openshift.selector("dc/${appname}").delete()
            }
          }
        }
      }
    }
    stage('Deploy in cicd-demo') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject("${buildproject}") {
              def dcSelector = openshift.selector("dc/${appname}")
              def RolloutMan = dcSelector.rollout()
              RolloutMan.latest()
              RolloutMan.status('-w')
            }
          }
        }
      }
    }

    stage('Test in builder project') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject(buildproject) {
              cicdRoute = openshift.selector("route/${appname}")
              host = cicdRoute.object().spec.host
              sh "rm -f koekjes"
              sh "curl -v --cookie-jar koekjes https://${host} |& grep -q 200"
            }
          }
        }
      }
    }
    stage('Ensure DeploymentConfig exists in testing') {
      when {
        expression {
          openshift.withCluster() {
            openshift.withProject("${testproject}") {
              return !openshift.selector("dc/${appname}").exists();
            }
          }
        }
      }
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject("${testproject}") {
              openshift.apply(openshift.process("-f", template, "-p NAME=${appname}"))
              openshift.selector("${buildconfig}").delete()
            }
          }
        }
      }
    }
    stage('Tag image from cicd to testing') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject("${buildproject}") {
              openshift.tag("${buildproject}/${appname}:latest", "${testproject}/${appname}:latest")
              openshift.tag("${buildproject}/${appname}:latest", "${testproject}/${appname}:${BUILD_ID}")
            }
          }
        }
      }
    }
    stage('Deploy in testing') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject("${testproject}") {
              newDeploy = openshift.selector("dc/${appname}").rollout()
              newDeploy.latest()
              newDeploy.status('-w')
            }
          }
        }
      }
    }
    stage('Ask for approval') {
      steps {
        script {
          openshift.withCluster() {
            input("Deploy to Production?")
          }
        }
      }
    }
    stage('Ensure DeploymentConfig exists in productie') {
      when {
        expression {
          openshift.withCluster() {
            openshift.withProject("${prodproject}") {
              return !openshift.selector("dc/${appname}").exists();
            }
          }
        }
      }
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject("${prodproject}") {
              openshift.apply(openshift.process("-f", template, "-p NAME=${appname}"))
              openshift.selector("${buildconfig}").delete()
            }
          }
        }
      }
    }
    stage('Tag image from test to productie') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject("${prodproject}") {
              openshift.tag("${testproject}/${appname}:latest", "${prodproject}/${appname}:latest")
              openshift.tag("${testproject}/${appname}:latest", "${prodproject}/${appname}:${BUILD_ID}")
            }
          }
        }
      }
    }
    stage('Deploy in Productie') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject("${prodproject}") {
              newDeploy = openshift.selector("dc/${appname}").rollout()
              newDeploy.latest()
              newDeploy.status('-w')
            }
          }
        }
      }
    }
  }
}
