apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}-pipeline
    name: ${APPLICATION_NAME}-pipeline
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: SerialLatestOnly
    source:
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: pipelines/Jenkinsfile
        env:
        - name: APPLICATION_NAME
          value: ${APPLICATION_NAME}
        - name: TEMPLATE
          value: ${TEMPLATE}
        - name: PROJECTBASE
          value: ${PROJECTBASE}
        - name: SOURCE_REPOSITORY_URL
          value: ${SOURCE_REPOSITORY_URL}
        - name: SOURCE_REPOSITORY_REF
          value: ${SOURCE_REPOSITORY_REF}
        - name: CONTEXT_DIR
          value: ${CONTEXT_DIR}
      type: JenkinsPipeline
    triggers: []
  status:
    lastVersion: 0
parameters:
- name: APPLICATION_NAME
  value: demo
- name: TEMPLATE
  value: templates/httpd-example.yaml
- name: PROJECTBASE
  value: demo
- name: SOURCE_REPOSITORY_URL
  value: https://gitlab.com/wanderb/cicd-demo.git
- name: SOURCE_REPOSITORY_REF
  value: master
- name: CONTEXT_DIR
  value: html
